### Proceso de limpieza EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings

In [4]:
# Carga del dataset
df_raw = pd.read_csv('../DATA/PROCESSED/student_performance.csv')

print(f"Registros: {df_raw.shape[0]}")
print(f"Columnas:  {df_raw.shape[1]}")

Registros: 1044
Columnas:  34

In [6]:
df_raw.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,subject
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,3,4,1,1,3,6,5,6,6,math
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,3,3,1,1,3,4,5,5,6,math
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,3,2,2,3,3,10,7,8,10,math
3,GP,F,15,U,GT3,T,4,2,health,services,...,2,2,1,1,5,2,15,14,15,math
4,GP,F,16,U,GT3,T,3,3,other,other,...,3,2,1,2,5,4,6,10,10,math

In [7]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 1044 entries, 0 to 1043
Data columns (total 34 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      1044 non-null   str
 1   sex         1044 non-null   str
 2   age         1044 non-null   int64
 3   address     1044 non-null   str
 4   famsize     1044 non-null   str
 5   Pstatus     1044 non-null   str
 6   Medu        1044 non-null   int64
 7   Fedu        1044 non-null   int64
 8   Mjob        1044 non-null   str
 9   Fjob        1044 non-null   str
 10  reason      1044 non-null   str
 11  guardian    1044 non-null   str
 12  traveltime  1044 non-null   int64
 13  studytime   1044 non-null   int64
 14  failures    1044 non-null   int64
 15  schoolsup   1044 non-null   str
 16  famsup      1044 non-null   str
 17  paid        1044 non-null   str
 18  activities  1044 non-null   str
 19  nursery     1044 non-null   str
 20  higher      1044 non-null   str
 21  internet    1044 non-null   str
 22  romantic    1044 non-null   str
 23  famrel      1044 non-null   int64
 24  freetime    1044 non-null   int64
 25  goout       1044 non-null   int64
 26  Dalc        1044 non-null   int64
 27  Walc        1044 non-null   int64
 28  health      1044 non-null   int64
 29  absences    1044 non-null   int64
 30  G1          1044 non-null   int64
 31  G2          1044 non-null   int64
 32  G3          1044 non-null   int64
 33  subject     1044 non-null   str
dtypes: int64(16), str(18)
memory usage: 277.4 KB

### Nulos

In [13]:
df_raw.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
subject       0
dtype: int64

### Duplicados

In [14]:
df_raw.duplicated().sum()

np.int64(0)

### Stats basicas

In [15]:
df_raw.describe().transpose()

             count       mean       std   min   25%   50%   75%   max
age         1044.0  16.726054  1.239975  15.0  16.0  17.0  18.0  22.0
Medu        1044.0   2.603448  1.124907   0.0   2.0   3.0   4.0   4.0
Fedu        1044.0   2.387931  1.099938   0.0   1.0   2.0   3.0   4.0
traveltime  1044.0   1.522989  0.731727   1.0   1.0   1.0   2.0   4.0
studytime   1044.0   1.970307  0.834353   1.0   1.0   2.0   2.0   4.0
failures    1044.0   0.264368  0.656142   0.0   0.0   0.0   0.0   3.0
famrel      1044.0   3.935824  0.933401   1.0   4.0   4.0   5.0   5.0
freetime    1044.0   3.201149  1.031507   1.0   3.0   3.0   4.0   5.0
goout       1044.0   3.156130  1.152575   1.0   2.0   3.0   4.0   5.0
Dalc        1044.0   1.494253  0.911714   1.0   1.0   1.0   2.0   5.0
Walc        1044.0   2.284483  1.285105   1.0   1.0   2.0   3.0   5.0
health      1044.0   3.543103  1.424703   1.0   3.0   4.0   5.0   5.0
absences    1044.0   4.434866  6.210017   0.0   0.0   2.0   6.0  75.0
G1          1044.0  11.213602  2.983394   0.0   9.0  11.0  13.0  19.0
G2          1044.0  11.246169  3.285071   0.0   9.0  11.0  13.0  19.0
G3          1044.0  11.341954  3.864796   0.0  10.0  11.0  14.0  20.0

### Se crea la variable objetivo para el modelo 2
### Multiclase: Clasificar nivel de riesgo académico (Sin riesgo/Riesgo bajo/Riesgo medio/Riesgo alto)

In [16]:
def obj_riesgo(g3):
    if g3 >= 14:   return 'Sin riesgo'
    elif g3 >= 10: return 'Riesgo bajo'
    elif g3 >= 7:  return 'Riesgo medio'
    else:          return 'Riesgo alto'

df_raw['risk_level'] = df_raw['G3'].apply(obj_riesgo)

risk_order = ['Sin riesgo', 'Riesgo bajo', 'Riesgo medio', 'Riesgo alto']
df_raw['risk_level'] = pd.Categorical(df_raw['risk_level'], categories=risk_order, ordered=True)

print(df_raw['risk_level'].value_counts().sort_index())

risk_level
Sin riesgo      294
Riesgo bajo     520
Riesgo medio    149
Riesgo alto      81
Name: count, dtype: int64